### PR TITLE
fix(R linting): try installing the R package before linting R language

### LINKED ISSUE #1910: R linter run by super-linter gives false positives
## Describe the bug

super-linter gives false positives when linting R language. super-linter uses [lintr](https://github.com/jimhester/lintr/) to lint R language files. If a linted github repository contains an R library (package), then lintr assumes that the package is installed. Otherwise, it detects false positives (specifically lintr's object_usage_linter).

## Expected behavior

super-linter does not return false positives when linting R language.

## Steps to Reproduce

I have run super-linter docker locally with the recommended arguments to provide a log. Here is the repo with the log: https://github.com/kpagacz/superlintertest

This particular lint is not present when lintr is run locally after installing the package (excerpt from super-linter.log)
```
2021-08-31 04:36:28 [ERROR]   Found errors in [R] linter!
2021-08-31 04:36:28 [ERROR]   Error code: 31. Command output:
------
/tmp/lint/R/test.R:5:9: warning: no visible binding for global variable ‘NS’
  ns <- NS
        ^~
------
2021-08-31 04:36:28 [DEBUG]   Error code: 31. Command output:
------
/tmp/lint/R/test.R:5:9: warning: no visible binding for global variable ‘NS’
  ns <- NS
        ^~
------
```

Excerpt from my command line:
```
r$> devtools::install('superlintertest')            
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                
2: CRAN packages only                 
3: None                               
4: R6        (2.5.0   -> 2.5.1) [CRAN]
5: htmltools (0.5.1.1 -> 0.5.2) [CRAN]
6: later     (1.2.0   -> 1.3.0) [CRAN]
7: cachem    (1.0.5   -> 1.0.6) [CRAN]
8: httpuv    (1.6.1   -> 1.6.2) [CRAN]

Enter one or more numbers, or an empty line to skip 
updates: 3                                          
   checking for file ‘/home/rstudio/projects/superli✔  checking for file ‘/home/rstudio/projects/superlintertest/DESCRIPTION’
─  preparing ‘superlintertest’: (366ms)
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘superlintertest_0.0.0.9000.tar.gz’
   
Running /usr/local/lib/R/bin/R CMD INSTALL \
  /tmp/Rtmp8AWMHc/superlintertest_0.0.0.9000.tar.gz \
  --install-tests 
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘superlintertest’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (superlintertest)

r$> lintr::lint_package('superlintertest')
.          
```

## Logs

Logs are in the linked repository, but here is the link to the file anyway: https://github.com/kpagacz/superlintertest/blob/main/super-linter.log

## Additional context

We are using super-linter to lint our R packages in the organization and we would really appreciate if super-linter behaved the same way as do the native R linting tools.

### PR DESCRIPTION
**Pull request by kpagacz**
* the tool used to lint the R language gives false positives for files inside an R library, which is not installed
* this change tries to naively install the package in the linted directory

Fixes #1910

I am not particularly experienced in Bash and this is my first PR to this repository, so I would welcome any guidance regarding styling, direction etc.

## Proposed Changes

1. Given the R language files to lint, try to install the R package from the working directory.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

File: lib/functions/detectFiles.sh [hunk 1]
```diff
@@ -437,4 +437,49 @@ function RunAdditionalInstalls() {
...
+
+    ##############################
+    # Check the shell for errors #
+    ##############################
+    if [ "${ERROR_CODE}" -ne 0 ]; then
+      # Error
+      warn "ERROR! Failed to run:[R CMD build] at location:[${WORKSPACE_PATH}]"
+    else
+      # Get the build package
+      BUILD_PKG=$(echo *.tar.gz)
```
Comment (admiralAwkbar) [inline lib/functions/detectFiles.sh:465]: @kpagacz  
I'm not 100% sure how this command is working, but the other 2 make sense :)

So we do a quick check to see if we are validating `R` files, and that we do have `R` files to validate, then we run this block of code.

I set it to `warn` and not `error` as I'm guessing some people don't have build packages in their repo, and that would cause failures to install something that isn't there...

thoughts?

**Review by admiralAwkbar — COMMENTED** [review]
@kpagacz
Sorry for such a delay on this. Have not had a lot of time lately and have been in maint mode.
Let me know if this looks good to you :)

thanks!

File: lib/functions/detectFiles.sh (hunk 1 above)
Comment (kpagacz) [reply lib/functions/detectFiles.sh:465]: Didn't find the Additional Installs section when I was looking through the code. Thanks for moving it here and all the improvements. My inexperience in bash is certainly showing here.

I agree this line is the weakest link. R CMD build outputs a .tar.gz file with the built package but does not give any options to customize the target path. I can try to regex the line with .tar.gz from the standard output of R CMD build (because the output from the command contains a line with the target file name) and extract the file name that way. I am unsure what's the safest way to proceed here as well. 

Do you have a preference?

**Comment by admiralAwkbar** [comment]
@kpagacz If you can give me some example code to run the r build command on, I should be able to get the last piece of this done :)
Just not familiar with the language, but if I had access to some test code I can write the last bash :)

**Comment by kpagacz** [comment]
Thank you very much for taking this over. 

I created an empty R repository: https://github.com/kpagacz/r-test-package

You can clone it and then run the command `R CMD build r-test-pacakge` and `R CMD INSTALL <path to the result of the first command>`. Run the commands in the directory containing the r-test-package directory (given directory structure /path/to/repo/here/r-test-package run the commands in the 'here' directory).

**Comment by admiralAwkbar** [comment]
@kpagacz Thanks for the test code! Thats all I needed to get this right :)

SHould be able to merge once tests pass
