### PR TITLE
fixed ansible and powershell

### LINKED ISSUE #260: PowerShell linter: /github/workspace/.automation/test: No such file or directory
**Describe the bug**
I try PowerShell Linter on one of PowerShell module ( https://github.com/FortiPower/PowerFGT) and get an error (See my commit https://github.com/alagoutte/PowerFGT/tree/super-linter )

**To Reproduce**
using PowerShell linter, i get the following error on the log :
/action/lib/linter.sh: line 1825: cd: /github/workspace/.automation/test: No such file or directory...
You can see log https://github.com/alagoutte/PowerFGT/runs/799749056?check_suite_focus=true

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This should solve a bug with folders on `powershell` and some hard coding of `ansible`
Closes #260

### CODE REVIEW

File: lib/linter.sh [hunk 1]
```diff
@@ -114,16 +114,16 @@ ACTIONS_RUNNER_DEBUG="${ACTIONS_RUNNER_DEBUG}"  # Boolean to see even more info
...
-DEFAULT_TEST_CASE_RUN='false'                         # Flag to tell code to run only test cases
-DEFAULT_ACTIONS_RUNNER_DEBUG='false'                  # Default value for debugging output
-RAW_FILE_ARRAY=()                                     # Array of all files that were changed
-READ_ONLY_CHANGE_FLAG=0                               # Flag set to 1 if files changed are not txt or md
-TEST_CASE_FOLDER='.automation/test'                   # Folder for test cases we should always ignore
-DEFAULT_DISABLE_ERRORS='false'                        # Default to enabling errors
+DEFAULT_VALIDATE_ALL_CODEBASE='true'                    # Default value for validate all files
+DEFAULT_WORKSPACE="${DEFAULT_WORKSPACE:-/tmp/lint}"     # Default workspace if running locally
+DEFAULT_ANSIBLE_DIRECTORY="$GITHUB_WORKSPACE/ansible"   # Default Ansible Directory
+DEFAULT_RUN_LOCAL='false'             # Default value for debugging locally
```
Comment (IAmHughes) [inline lib/linter.sh:120]: Non-blocking comment, just curious if you wanted to align the comments from lines 120-126 with the above comments.

Other than that, LGTM, I think this will fix the error.

Comment (admiralAwkbar) [reply lib/linter.sh:120]: lol man... ill leave it for now
